### ISSUE TITLE
The UPC portion test failed after entering more than 12 numbers

### ISSUE THREAD

**Issue by thomasejohns** [danac78/CTUMart#12]
1. Go to the product search page.
2. select UPC
3. enter 13 characters
4. Click on Submit
5. Does NOT give error message.

**Comment by danac78** [comment]
For some reason, the way it was written was causing it to be bypassed. So I changed it so it is checking a string rather than the edit box itself. Although there should not be any difference, it just was not working correctly the other way.

**Comment by danac78** [comment]
Was going to fix this tomorrow..but they were easy ones. The first one was
due to /n .. Android follows a linux style..so it should have been \n. And
the other issue involved putting a String. For some reason, it did not like
the two else statemets with android. so I made a string to accomplish this.
