### ISSUE TITLE
Values are not being passed

### ISSUE THREAD

**Issue by danac78** [danac78/CTUMart#5]
Since I am the one writing the code, it might because there are no values to pass with intent. Not sure if this is a bug with Intent or something. I might fixed this by making a helper class just for these values.

**Comment by danac78** [comment]
Changed the method of passing the information from Intent to using SharedPreferences. This ensures that all the information is stored correctly and retrieved.

**Comment by thomasejohns** [comment]
I am trying to get the website to connect to the database. I think I am just going to host the db on my home computer and connect to it. That way I can manage it a little easier.

Thank you,
Thomas Johns

-----Original Message-----
From: danac78 [mailto:reply@reply.github.com] 
Sent: Saturday, July 21, 2012 1:45 PM
To: thomasejohns
Subject: [CTUMart] Values are not being passed (#5)

Since I am the one writing the code, it might because there are no values to pass with intent. Not sure if this is a bug with Intent or something. I might fixed this by making a helper class just for these values.

---

Reply to this email directly or view it on GitHub:
https://github.com/danac78/CTUMart/issues/5

**Comment by danac78** [comment]
Ok doke.

On Sun, Jul 22, 2012 at 10:33 AM, thomasejohns <
reply@reply.github.com

**Comment by thomasejohns** [comment]
OK, so I got a connection to the database and added the store data you emailed me. I added zip and made up addresses and phone numbers. Here is a link to the add data page. http://www.fuelradio.fm/ctumart/addstuff.php

Here is the login info for the data base:

Database: tommyj_ctumart
Username: tommyj_ctu123
Password: abc123xyz

I'll try and setup an ftp and a remote access to the db for the app.

Thank you,
Thomas Johns

-----Original Message-----

**Comment by danac78** [comment]
Umm..Tom..We don't need a remote access to the db for the app (unless I am
missing what you mean). If the website is connected, that all we need. The
Android App is going to read the webpage information.;) I forgot the zip?
GASP! Sorry..brain fart.

On Sun, Jul 22, 2012 at 5:58 PM, thomasejohns <
reply@reply.github.com

**Comment by thomasejohns** [comment]
Ah, ok.

Thank you,
Thomas Johns

-----Original Message-----

**Comment by danac78** [comment]
The only reason I wanted ftp access is so if I need to fix something with
the PHP..I can do so and send you the note what I did.

On Sun, Jul 22, 2012 at 6:30 PM, thomasejohns <
reply@reply.github.com

**Comment by thomasejohns** [comment]
FTP username: dana@therefineryrock.com
FTP server: ftp.therefineryrock.com
FTP & explicit FTPS port: 21
FTP Password: %kHUEd~NqXaL

Thank you,
Thomas Johns

-----Original Message-----

**Comment by thomasejohns** [comment]
I don't have the login done yet but here is yours
Username: danac78
Password: admin246

Thank you,
Thomas Johns

-----Original Message-----

**Comment by danac78** [comment]
Awesome. :)

On Thu, Jul 26, 2012 at 7:48 PM, thomasejohns <
reply@reply.github.com
